### ISSUE TITLE
winpty aborts immediately and leaves shell in weird state

### ISSUE THREAD

**Issue by jiixyj** [rprichard/winpty#95]
I try to run winpty 0.4.1 with the following command (Windows 7, git shell or msys2 shell, doesn't matter):

    WINPTY_DEBUG=trace WINPTY_SHOW_CONSOLE=1 ./winpty.exe powershell

The console window opens for a split second, then closes. There is no output in the shell where winpty was started. The shell is now in a weird state: Pressing keys does not result in any output. Pressing enter works. Blindly entering a command, then pressing enter executes the command, but the output is garbled (line endings are ignored/formatted weird). Running "reset" restores the correct shell behavior.

Do you have any idea why winpty won't work? It used to work fine in the past. Still, winpty 0.2.1 also shows this behavior now. Is there a way I can debug this further?

Here is the output of `winpty-debugserver.exe`:
```
[23985.980 winpty.exe,p8384,t7216]: Windows version: 6.1.7601 SP1.0 Client X64 kernel32.dll:F:6.1.7601.23572/P:6.1.7601.23572 ConEmuHk64.dll:none
[23985.980 winpty.exe,p8384,t7216]: winpty version 0.4.1 (commit ff8e67d31397adb9fdacd770540cd58debad32fd)
[23986.034 winpty.exe,p8384,t7216]: Created agent successfully, pid=1372, cmdline="XXX\winpty-0.4.1-msys2-2.5.1-x64\bin\winpty-agent.exe" \\.\pipe\winpty-control-8384-1-1d26671473ef96c-7f7169aefcf56e7f7457313c4fac5c25 8 1 132 48
[23986.089 winpty-agent.exe,p1372,t1472]: Windows version: 6.1.7601 SP1.0 Client X64 kernel32.dll:F:6.1.7601.23572/P:6.1.7601.23572 ConEmuHk64.dll:none
[23986.089 winpty-agent.exe,p1372,t1472]: winpty version 0.4.1 (commit ff8e67d31397adb9fdacd770540cd58debad32fd)
[23986.090 winpty-agent.exe,p1372,t1472]: Agent::Agent entered
[23986.090 winpty-agent.exe,p1372,t1472]: connected to [\\.\pipe\winpty-control-8384-1-1d26671473ef96c-7f7169aefcf56e7f7457313c4fac5c25], handle == 00000000000000AC
[23986.092 winpty-agent.exe,p1372,t1472]: opened server pipe [\\.\pipe\winpty-conin-1372-1-1d26671474f9b3c-e7dc16c4676dd73db1e15ef4dbeebe2d], handle == 00000000000000BC
[23986.092 winpty-agent.exe,p1372,t1472]: opened server pipe [\\.\pipe\winpty-conout-1372-2-1d26671474fe95c-eaaf8c2f9f948d0d0ead60a4cf2db800], handle == 00000000000000EC
[23986.093 winpty-agent.exe,p1372,t1472]: setSmallFont: attempting to set a small font for 132 columns (CP=437 OutputCP=437)
[23986.093 winpty-agent.exe,p1372,t1472]: previous font: nFont=0 dwFontSize=(9,20) FontFamily=0x36 FontWeight=400 FaceName=Consolas (43 6F 6E 73 6F 6C 61 73)
[23986.093 winpty-agent.exe,p1372,t1472]: previous font table: fonts 00-02:  9x20  9x20 10x20
[23986.093 winpty-agent.exe,p1372,t1472]: setFontVista: setting font to: nFont=0 dwFontSize=(0,5) FontFamily=0x36 FontWeight=400 FaceName=Lucida Console (4C 75 63 69 64 61 20 43 6F 6E 73 6F 6C 65)
[23986.096 winpty-agent.exe,p1372,t1472]: setSmallFontVista: success
[23986.096 winpty-agent.exe,p1372,t1472]: new font: nFont=0 dwFontSize=(3,5) FontFamily=0x36 FontWeight=400 FaceName=Lucida Console (4C 75 63 69 64 61 20 43 6F 6E 73 6F 6C 65)
[23986.097 winpty-agent.exe,p1372,t1472]: new font table: fonts 00-04:  3x5   4x5   9x20  9x20 10x20
[23986.112 winpty-agent.exe,p1372,t1472]: CONIN modes: Extended=on, MouseInput=on QuickEdit=on EscapeInput=off
[23986.112 winpty-agent.exe,p1372,t1472]: Server pipe [\\.\pipe\winpty-conin-1372-1-1d26671474f9b3c-e7dc16c4676dd73db1e15ef4dbeebe2d] connected
[23986.112 winpty-agent.exe,p1372,t1472]: Server pipe [\\.\pipe\winpty-conout-1372-2-1d26671474fe95c-eaaf8c2f9f948d0d0ead60a4cf2db800] connected
[23986.121 winpty-agent.exe,p1372,t1472]: CreateProcess: success 8872
[23986.154 winpty-agent.exe,p1372,t1472]: Agent exiting (control pipe is closed)
[23986.155 winpty-agent.exe,p1372,t1472]: Agent::~Agent entered
```

**Comment by rprichard** [comment]
I don't have any idea so far.  What does your `uname -a` report?  I'm also using a 64-bit Win7 machine, with version 2.5.2 of the Cygwin DLL:

```
$ uname -a
CYGWIN_NT-6.1 VBWIN7 2.5.2(0.297/5/3) 2016-06-23 14:29 x86_64 Cygwin
```

**Comment by rprichard** [comment]
Well, I *do* have some idea of what's happening -- it looks like the Cygwin program `winpty.exe` is successfully starting up, reconfigures the pty and connects to the winpty agent, but then it suddenly disconnects from the agent.  I'm guessing it's crashing?

**Comment by jiixyj** [comment]
Here the output of `uname -a`:

    MINGW64_NT-6.1 XXX 2.6.0(0.304/5/3) 2016-09-09 09:46 x86_64 Msys

Another data point: Sometimes, the console (WINPTY_SHOW_CONSOLE) stays up for 2-3 seconds and I see the commands output. The output does not show up in the MinGW console, however.

**Comment by rprichard** [comment]
I installed Cygwin 2.6.1 into a new directory, and the shipped winpty binary worked there.

Can you build from source?  I could create a branch filled with trace() statements, and maybe that'd help.

Attaching gdb might help -- I think it can detect whether the program segfaults.  I tried making the program segfault deliberately, though, and it printed a "Segmentation fault" error to the Cygwin terminal, which you're not seeing.

**Comment by jiixyj** [comment]
Yes, I can try to build from source and debug further. I'll also try running winpty under gdb. Thanks for your help so far!

**Comment by jiixyj** [comment]
It looks like the Anti Virus (Trend Micro) on this computer is responsible.
Many people are hitting this with other Cygwin programs as well (e.g. https://cygwin.com/ml/cygwin/2016-09/msg00338.html).

So this is not a bug of winpty.

Here the backtrace of `gdb --args winpty powershell`:
```
(gdb) bt
#0  0x00000000773b470a in ntdll!LdrLoadAlternateResourceModule ()
   from /c/Windows/SYSTEM32/ntdll.dll
#1  0x00000000773bddd8 in ntdll!RtlAllocateHeap ()
   from /c/Windows/SYSTEM32/ntdll.dll
#2  0x0000000077441a5d in ntdll!EtwEventWriteStartScenario ()
   from /c/Windows/SYSTEM32/ntdll.dll
#3  0x00000000773dc985 in ntdll!TpAlpcRegisterCompletionList ()
   from /c/Windows/SYSTEM32/ntdll.dll
#4  0x00000000773bddd8 in ntdll!RtlAllocateHeap ()
   from /c/Windows/SYSTEM32/ntdll.dll
#5  0x0000000074d697bf in ?? ()
   from /c/Windows/system32/tmumh/20019/TmMon/1.6.0.1179/tmmon64.dll
#6  0x0000000074d694f7 in ?? ()
   from /c/Windows/system32/tmumh/20019/TmMon/1.6.0.1179/tmmon64.dll
#7  0x0000000074d02fe2 in ?? ()
   from /c/Windows/system32/tmumh/20019/TmMon/1.6.0.1179/tmmon64.dll
#8  0x0000000074d02d82 in ?? ()
   from /c/Windows/system32/tmumh/20019/TmMon/1.6.0.1179/tmmon64.dll
#9  0x0000000074d04989 in ?? ()
   from /c/Windows/system32/tmumh/20019/TmMon/1.6.0.1179/tmmon64.dll
#10 0x0000000074d048e1 in ?? ()
   from /c/Windows/system32/tmumh/20019/TmMon/1.6.0.1179/tmmon64.dll
#11 0x0000000074db4d83 in tmmon64!NullExport ()
   from /c/Windows/system32/tmumh/20019/TmMon/1.6.0.1179/tmmon64.dll
#12 0x0000000074db36e4 in tmmon64!NullExport ()
   from /c/Windows/system32/tmumh/20019/TmMon/1.6.0.1179/tmmon64.dll
#13 0x0000000074d1727d in ?? ()
   from /c/Windows/system32/tmumh/20019/TmMon/1.6.0.1179/tmmon64.dll
#14 0x00000001800b2bb4 in CreateMutexW () from /usr/bin/msys-2.0.dll
#15 0x000000018004417b in init_cygheap::add_tls(_cygtls*) ()
   from /usr/bin/msys-2.0.dll
#16 0x00000001800bd93c in pthread_wrapper () from /usr/bin/msys-2.0.dll
#17 0x000000018004579b in _cygtls::call2(unsigned int (*)(void*, void*), void*, void*) () from /usr/bin/msys-2.0.dll
#18 0x0000000180045804 in _cygtls::call(unsigned int (*)(void*, void*), void*)
    () from /usr/bin/msys-2.0.dll
#19 0x00000000772659cd in KERNEL32!BaseThreadInitThunk ()
   from /c/Windows/system32/kernel32.dll
#20 0x000000007739a561 in ntdll!RtlUserThreadStart ()
   from /c/Windows/SYSTEM32/ntdll.dll
#21 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by rprichard** [comment]
I'm glad you figured out the cause.

I considered suggesting, "maybe turn off an antivirus," but it would have been a shot in the dark, so I stayed quiet.  :)
